"""initial tables

Revision ID: 05677c1bb305
Revises: 
Create Date: 2025-09-25 15:01:57.476527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05677c1bb305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('employerID', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('employerID')
    )
    op.create_table('staff',
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('staffID'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student',
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('studentID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('internship_position',
    sa.Column('positionID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('employerID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employerID'], ['employer.employerID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['student.studentID'], ),
    sa.PrimaryKeyConstraint('positionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internship_position')
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_table('employer')
    # ### end Alembic commands ###
